### ISSUE TITLE
Can't get this to work with Home Assistant

### ISSUE THREAD

**Issue by bperkins011** [Fusion/pywhistle#1]
I've spend a few hours trying to get this installed. There are a few conflicting install methods which I'm sure have changed over time..
I'd love to do the home  assistant integration - but I can't seem to get the library/sensor to be recognized.

Is there a *current* install guide or maybe some info on what the directory structure should look like after install?
I can't get the sensor to show up in states..    
Thanks for the help if you can..

**Comment by Fusion** [comment]
Hi.

What version of HA are you running? I am currently on 0.96.3 and it was itself a rewrite after breaking changes in HA. If you are running something more recent, then I guess it's a motivation for me to upgrade :/

**Comment by Fusion** [comment]
Update: I upgraded to 0.101.3 and tested the configuration. I updated both the HA community topic and the README.md file in the example/ folder.

**Comment by bperkins011** [comment]
Very cool - thanks!I messed with it for a few hours trying to trick it into working..  But couldn't get the sensor to pop in..
I'm still finding my way around HA..If you added it to HACS - would that make it easier to maintain?  Either way - I'm looking forward to getting Ellie (our Golden) all tracked on HA.Thanks


Bob Perkins 
All the fun stuffhttps://bperkins.wordpress.com/ 

    On Sunday, November 17, 2019, 06:47:02 PM EST, Chris F Ravenscroft <notifications@github.com> wrote:  
 
 
Update: I upgraded to 0.101.3 and tested the configuration. I updated both the HA community topic and the README.md file in the example/ folder.

**Comment by Fusion** [comment]
It would not make it easier to maintain, but it would make it easier to install, so that's worth looking into :)

**Comment by bperkins011** [comment]
Hi Fusion - 
I tried again , but HA isn't picking up the device tracker in the States table 
![image](https://user-images.githubusercontent.com/40862414/69052633-8444b200-09d5-11ea-9564-0d61c05ba64b.png)

Is this all that is required - or is there another set of files needed to support these?
thanks again.

**Comment by bperkins011** [comment]
Wait - I figured it out..  The whistle ln -s doesn't seem to work in a docker container.  

I renamed the homeassistant directory and moved it up:
![image](https://user-images.githubusercontent.com/40862414/69054237-231edd80-09d9-11ea-9822-3beb95d3a68d.png)

That AND this forced HA to load the device..
![image](https://user-images.githubusercontent.com/40862414/69054307-45186000-09d9-11ea-83f8-2b4205bddf7c.png)

Thanks!

**Comment by Fusion** [comment]
Thanks that's good detective work!
Also, I'm an idiot: I just updated the README file so that `ln` now creates an absolute link.

**Comment by bperkins011** [comment]
Every little bit helps  - thank you  :)

**Comment by dylanmcdermott** [comment]
Also have a similar issue where cant get the device tracker to show up. I'm unable to pull the files in via git, can i copy the 3 files from github into custom_components/whistle/ via samba and expect that to work?

**Comment by Mrono** [comment]
I'm trying to set this up on HA 0.111.4, no errors except this one
 Platform error: device_tracker - Integration 'whistle' not found.

**Comment by joshvazquez** [comment]
[This change](https://github.com/Fusion/pywhistle/commit/2c6401c7dbdd42f4b3b8c56dcda8d264e133fa60) prevents the setup from working when done outside of the Docker container because the container doesn't have the same directory structure. I recommend creating the link from the custom_components folder instead of from the pywhistle folder.

In pywhistle folder, after `git checkout`, instead of `ln -s examples/homeassistant ../whistle`:
```
cd ..
ln -s pywhistle/examples/homeassistant whistle
```
This way is universal and will work whether you do it inside or outside of the container.

@dylanmcdermott @Mrono here's your solution

**Comment by joshvazquez** [comment]
#5

**Comment by Fusion** [comment]
Merged!
