### ISSUE TITLE
was 5here an API change? no longer working

### ISSUE THREAD

**Issue by dylanmcdermott** [Fusion/pywhistle#2]
Getting this error in the logs

Logger: custom_components.whistle.device_tracker
Source: custom_components/whistle/device_tracker.py:68
Integration: whistle (documentation)
First occurred: August 26, 2020, 8:16:10 AM (1116 occurrences)
Last logged: 9:26:26 PM

There was an error while updating: 401, message='Unauthorized', url='https://app.whistle.com/api/pets
There was an error while updating: 504, message='Gateway Time-out', url='https://app.whistle.com/api/pets
There was an error while updating: 502, message='Bad Gateway', url='https://app.whistle.com/api/pets
There was an error while updating: Cannot connect to host app.whistle.com:443 ssl:None [Try again]

**Comment by Fusion** [comment]
Not sure what happened there. Still working for me.

Try restarting home assistant. If you are not seeing the issue anymore, then it could be an expired token and it means I need to implement token re-up.

**Comment by Fusion** [comment]
Did you ever get to othe bottom of this?

**Comment by dbdmdbdmdbdm** [comment]
Hey @Fusion yeah we can close this issue
