### ISSUE TITLE
Permission Denied (publickey)

### ISSUE THREAD

**Issue by farberm** [Fusion/pywhistle#6]
when I use the git command I  Have the following error.
git@github.com: Permission denied (publickey)
fatal: Could not read from remote repository
![Screen Shot 2021-04-07 at 11 18 43 PM](https://user-images.githubusercontent.com/16128857/113963491-acfe5f00-97f7-11eb-9b76-4bda5cbea833.png)

**Comment by Fusion** [comment]
Good point. This will only work if you have a Github account that is configured on that machine.
I imagine that you could perform a clone from the https:// link instead:
```
git clone --depth=1 https://github.com/Fusion/pywhistle.git --no-checkout
```
(not tested but this should do the trick)
