### ISSUE TITLE
Whistle Warning No 'version' key

### ISSUE THREAD

**Issue by farberm** [Fusion/pywhistle#7]
I am getting the following warning that indicates that this will no longer work unless fixed in the near future. I am running 2021.4

WARNING:
No 'version' key in the manifest file for custom integration 'whistle'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'whistle'

I just installed this and it works great. Would be terriific if you could update this.

**Comment by spencer-scott** [comment]
I am also getting this same warning. I believe this is a new change they made in the 2021.4 release that custom integrations have to contain the version number in the manifest file now. Thanks for all your hard work on this integration!
